[first_page_urls]
ryans = "https://www.ryans.com/category/desktop-component-graphics-card?limit=100&sort=LH&osp=1&st=0"
startech = "https://www.startech.com.bd/component/graphics-card?filter_status=7&sort=p.price&order=ASC&limit=90"
creatus = "https://creatuscomputer.com/components/graphics-card?sort=p.price&order=ASC&fq=1&fmin=3000&fmax=300000&limit=100"
globalbrand = "https://www.globalbrand.com.bd/graphics-card?sort=p.price&order=ASC&limit=100&fmin=1000"
ultratech = "https://www.ultratech.com.bd/pc-components/graphics-card?sort=p.price&order=ASC&fq=1&limit=100"
nexusbd = "https://www.nexus.com.bd/graphics-card/?sort_by=price&sort_order=asc&layout=products_multicolumns&items_per_page=64&features_hash=13-Y"
techlandbd = "https://www.techlandbd.com/pc-components/graphics-card?sort=p.price&order=ASC&fq=1&limit=100"
uccbd = "https://www.ucc.com.bd/category-store/computer-components/graphics-card?sort=p.price&order=ASC&fq=1&limit=100"
skyland = "https://www.skyland.com.bd/components/graphics-card?sort=p.price&order=ASC&limit=100&fq=1"

[gpu_name_css_selectors]
ryans = "p.card-text.p-0.m-0.grid-view-text > a"
startech = "h4.p-item-name > a"
techlandbd = "div.name > a"
skyland = "div.name > a"
ultratech = "div.name > a"
nexusbd = "h2 > a.product-title"
globalbrand = "div.name > a"
creatus = "div.caption > div.name > a"
uccbd = "div.caption > div.name > a"

[price_css_selectors]
ryans = "a.pr-text.cat-sp-text.pb-1"
startech = "div.p-item-price > span"
techlandbd = "div.price > div > span"
skyland = "div.price > div > span"
ultratech = "div.price > div > span"
nexusbd = "span.ty-price > bdi > span ~ span"
globalbrand = "div.price > div > span"
creatus = "div.price > div > span"
uccbd = "div.price > div > span"

[retailers]
ryans = "Ryans Computer"
startech = "Startech Engineering"
techlandbd = "Tech Land BD"
skyland = "Skyland Computer Bd"
ultratech = "Ultra Technology"
nexusbd = "Nexus Technology"
globalbrand = "Global Brand"
creatus = "Creatus Computer"
uccbd = "UCC-BD"
