name: CI/CD

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      test_db_url: ${{secrets.test_db_url}}
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
        
      - name: Install gpu4bdgamers
        run: |
          pip install .
      
      - name: Run Integration Test
        env: 
          PROJECT_ROOT: ${{github.workspace}}
        run: |
          mkdir logs
          mkdir tests/integration_test/logs
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Railway CLI
      run: curl -fsSL https://railway.app/install.sh | sh

    - name: Login to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway login --token $RAILWAY_TOKEN

    - name: Deploy to Railway
      run: railway up