name: Daily Data Scraping

on:
    schedule: 
        - cron: 0 15 * * *

jobs:
  scraping:
    runs-on: ubuntu-latest

    env:
      test_db_url: ${{secrets.test_db_url}}
      db_url_new: ${{secrets.db_url_new}}
      scraperapi_api_key: ${{secrets.scraperapi_api_key}}

    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements_dev.txt
        
      - name: Install gpu4bdgamers
        run: |
          pip install .
      
      - name: Run Integration Test
        run: |
          cd tests/integration_test
          mkdir logs
          pytest

      - name: Run Scraping
        run: |
          cd ../../
          l

      - name: Upload logs as artifact
        run: |
          logs/gpu_data_coll_script.log
