name: Integration Test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      test_db_url: ${{secrets.test_db_url}}
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
        
      - name: Install gpu4bdgamers
        run: |
          pip install .
      
      - name: Run Integration Test
        run: |
          set PROJECT_ROOT=$(pwd)
          mkdir logs
          mkdir tests/integration_test/logs
          pytest